#!/bin/sh

git filter-branch --commit-filter '
        if [ "$GIT_COMMITTER_NAME" = "Vinit Kanani" ];
        then
                GIT_COMMITTER_NAME="Rishikesh Andhare";
                GIT_AUTHOR_NAME="Rishikesh Andhare";
                GIT_COMMITTER_EMAIL="rishikeshandhare95@gmail.com";
                GIT_AUTHOR_EMAIL="rishikeshandhare95@gmail.com";
                git commit-tree "$@";
        else
                git commit-tree "$@";
        fi' HEAD
